apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: website
build:
  artifacts:
  - image: 816119410753.dkr.ecr.us-east-2.amazonaws.com/flexable-website
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    defaultNamespace: flexable
    manifests:
    - k8s/website-deploy.yml
    - k8s/website-ingress.yml
    - k8s/website-service.yml
